feat: Add Sniffer Lora
ElectronicCats/CatSniffer-Firmware pull request #5
Opened 2024-10-23 17:32 UTC by JahazielLem

- Lora Sniffer with PyCatsniffer support

2024-10-28 17:13 UTC, Marcelol52 commented
Valida bien todas las opciones al generar el comando excepto por el valor del canal.

2024-10-29 17:39 UTC, sabas1080 requested changes
problema en el valor del canal

2024-10-29 17:49 UTC, JahazielLem commented
> problema en el valor del canal

Esto ya quedo solucionado era error en la validacion del catnip

2024-10-29 17:55 UTC, sabas1080 approved these changes

2024-10-29 19:49 UTC, merged